spring.config.import=optional:file:.env[.properties]
spring.application.name=tasks
spring.profiles.active=dev
#spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/clientproj1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@Gischellatte96
spring.jpa.properties.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=${JWT_TOKEN_EXPIRY}